project:
  type: website
  output-dir: docs

website:
  title: "A Point in Time"
  navbar:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/dawnngalloway/
      - icon: github
        href: https://github.com/DawnGalloway
      - href: blog.qmd
        text: Blog
      - about.qmd
      
format:
  html:
    theme: lux
    css: bootstrap.min.css



