---
title: "Forecast Intro"
author: "Dawn Galloway"
date: "2022-10-17"
categories: [senior project, Forecast]
---

### Forecast: The Basics

##### Resources

The first thing you need to know about the Forecast package is that there is an incredibly helpful text by Rob J Hyndman and George Athanasopoulos titled [Forecasting: Principles and Practice](https://otexts.com/fpp2/) which explains relevant concepts and walks through almost every function with examples. If you would like to work through their examples, you can download the fpp2 package which includes Forecast and all of the data. I wish every package had such a helpful guide.<br>

Some other useful resources:

* The Forecast package manual and vignette is available [here](https://cran.r-project.org/web/packages/forecast/index.html)
* [Hyndsight](https://robjhyndman.com/hyndsight/), Rob J. Hyndman's blog
* [Cross Validated](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiQ7oL92fH6AhUYAjQIHaC9BpAQFnoECAwQAw&url=https%3A%2F%2Fwww.kdnuggets.com%2F2011%2F10%2Fcross-validated-statistical-stackexchange.html&usg=AOvVaw3vmgU60Gt_FJswas7T-B_R), Stack Exchange's Q&A for Statistical Topics

Hyndman pretty actively answers questions both on his blog and on Cross Validated, so I suggest reading the comments if your question isn't answered in a blog entry.<br><br>


##### General Tips

When they refer to a time series, they are not referring to data with time information. They are referring to a specific data type, the time series. 

```{r warning=FALSE, message=FALSE}
#install.packages("fpp2")
library(fpp2)
head(Nile)
head(goog200)
```
Unlike a data frame or tibble, there isn't a column for times, rather a time series has a starting point, an ending point, and a frequency. Typically, a frequency of 1 is annual, 4 is quarterly, 12 is monthly, and so on. The start year for the Nile data is 1871, while the start for the Google daily closing stock price is arbitrary, representing an undated year.<br><br>
