project:
  type: website
  output-dir: docs

website:
  title: "A Point in Time"
  navbar:
    right:
      - icon: github
        href: https://github.com/DawnGalloway
      - href: myblog
        text: Blog
      - about.qmd

format:
  html:
    theme: lux
    css: bootstrap.min.css



